/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.Timer;


public class Opening extends javax.swing.JFrame {

    /**
     * Creates new form Opening
     */
    public Opening() {
    initComponents();
    setSize(600,600);
    setLocationRelativeTo(null);
    setLayout(null);
    setResizable(false);

    JLabel bgLabel = new JLabel();
    bgLabel.setBounds(0,0,600,600);
    bgLabel.setLayout(null);

    try {
        java.net.URL url = getClass().getResource("/View/bank_background_v3.png");
        System.out.println("Resource URL: " + url);

        if (url == null) {
            System.out.println("ERROR: Image not found on classpath. "
                + "Check that bank_background_v3.png is inside build/classes/View/ after a Clean and Build.");
        } else {
            Image img = ImageIO.read(url);
            Image scaled = img.getScaledInstance(600, 600, Image.SCALE_SMOOTH);
            bgLabel.setIcon(new ImageIcon(scaled));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    add(bgLabel);

    GlassPanel glass = new GlassPanel();
    glass.setBounds(80, 180, 440, 240);
    glass.setLayout(null);
    bgLabel.add(glass);


    JLabel timeLabel = new JLabel();
    timeLabel.setBounds(30, 30, 300, 50);
    timeLabel.setForeground(Color.WHITE);
    timeLabel.setFont(new Font("Segoe UI", Font.BOLD, 36));
    glass.add(timeLabel);

    JLabel dateLabel = new JLabel();
    dateLabel.setBounds(30, 80, 300, 30);
    dateLabel.setForeground(new Color(230, 230, 230));
    dateLabel.setFont(new Font("Segoe UI", Font.PLAIN, 16));
    glass.add(dateLabel);

    JButton enterBtn = new JButton("ENTER SYSTEM");
    enterBtn.setBounds(130, 150, 180, 40);
    enterBtn.setFocusPainted(false);
    enterBtn.setBorderPainted(false);
    enterBtn.setForeground(Color.WHITE);
    enterBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
    enterBtn.setBackground(new Color(30, 90, 170));
    glass.add(enterBtn);


    Timer timer = new Timer(1000, e -> {
        timeLabel.setText(
            LocalTime.now().format(
                DateTimeFormatter.ofPattern("hh:mm a")
            )
        );

        dateLabel.setText(
            LocalDate.now().format(
                DateTimeFormatter.ofPattern("MMM dd, yyyy")
            )
        );
    });
    timer.start();
    enterBtn.addActionListener(e -> {
        new LoginFrame().setVisible(true);
        dispose();
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
